### ISSUE TITLE
Reproduce for Dual-Prompt

### ISSUE THREAD

**Issue by misty0729** [Lee-JH-KR/l2p-pytorch#1]
Hi,

Thanks for your great job, will you implement Dual-Prompt with pytorch later?

Best,
Zi

**Comment by Lee-JH-KR** [comment]
Hi,
Thank you for your interest.

Pytorch implementation of Dual-Prompt has been completed. 
Some tests are left, and it will be released in a few days.

Best,
Jaeho Lee

**Comment by ZhangzihanGit** [comment]
> Hi, Thank you for your interest.
> 
> Pytorch implementation of Dual-Prompt has been completed. Some tests are left, and it will be released in a few days.
> 
> Best, Jaeho Lee

Hi Jaeho, thank you very much for your contribution!! I'm wondering if the Dual-Prompt implementation is ready. Much appreciated!

**Comment by Lee-JH-KR** [comment]
Hi, @ZhangzihanGit 
Thank you for your interest.

The first commit was completed about a month ago.

I'm linking the its repository, so please check it out.
[https://github.com/Lee-JH-KR/dualprompt-pytorch](https://github.com/Lee-JH-KR/dualprompt-pytorch)

Best,
Jaeho Lee.
