### ISSUE TITLE
Question about the classification head layer

### ISSUE THREAD

**Issue by YananGu** [Lee-JH-KR/l2p-pytorch#7]
Hi, I am very interested in your work, and your reproduction work contributes a lot to the incremental learning community.

In the process of studying the code, I found that the classification layer is only updated at the first task, and then no longer updated in subsequent tasks, is this normal? Is the official code also set up like this?  Look forward to your answer,

**Comment by YananGu** [comment]
Sorry I read it wrong, the classification head layer is updating.

**Comment by prachigarg23** [comment]
Hi @YananGu , can you please point me to where in the code is the classifier layer being initialized and updated?

**Comment by YananGu** [comment]
Hi @prachigarg23,  the classifier layer is defined in line 410 of vision_transformer.py.

        self.head = nn.Linear(self.embed_dim, num_classes) if num_classes > 0 else nn.Identity()
